:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:timeout: 8
:max_retries: 3
:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]

development:
  :concurrency: 5

test:
  :concurrency: 1

production:
  :concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 10) %>
  :timeout: <%= ENV.fetch('SIDEKIQ_TIMEOUT', 8) %>
  :max_retries: <%= ENV.fetch('SIDEKIQ_MAX_RETRIES', 3) %> 